# scale-config.yml:
#   Powers what instance types are available for GHA auto-scaled
#   runners. Runners listed here will be available as self hosted
#   runners, configuration is directly pulled from the main branch.
#
# NOTE (Apr, 5, 2021): Linux runners are currently all an amazonlinux2
#
# NOTE (Jan 5, 2021): Linux runners are all non-ephemeral to reduce the amount of CreateInstaces calls
#                     to avoid RequestLimitExceeded issues
#
# TODO: Add some documentation on how the auto-scaling works
#
# NOTE: Default values,
#
# runner_types:
#   runner_label:
#     instance_type: m4.large
#     os: linux
#     max_available: 20
#     disk_size: 50
#     is_ephemeral: true

runner_types:
  # mainly used for ciflow-should-run, not made to run any serious tests
  linux.large:
    instance_type: c5.large
    os: linux
    disk_size: 10
    is_ephemeral: false
  linux.2xlarge:
    instance_type: c5.2xlarge
    os: linux
    max_available: 500
    disk_size: 150
    is_ephemeral: false
  # 8xV100 (32GB) GPU instance, 96 vCPU, 768 GB RAM
  linux.p324xlarge.nvidia.gpu:
    instance_type: p3dn.24xlarge
    os: linux
    max_available: 1
    disk_size: 512
    is_ephemeral: false
  # 8xA100 GPU (40GB) instance, 96 vCPU, 1152 GB RAM
  linux.p4d24xlarge.nvidia.gpu:
    instance_type: p4d.24xlarge
    os: linux
    max_available: 1
    disk_size: 512
    is_ephemeral: false
