models:
  - "detectron2_.*"
device:
  - "cuda"
test:
  - "eval"
batch_size:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
args:
  - ""
  - "--resize 448x608"
  - "--torchdynamo fx2trt"
  - "--torchdynamo fx2trt --resize 448x608"
