cuda:
  - version: 11.3
    magma_version: magma-cu113
  - version: 11.6
    magma_version: magma-cu116
pytorch:
  - version: 1.12.1
    conda_channel: pytorch-test
  - version: 1.12.0
    conda_channel: pytorch
