cuda:
  - version: 11.6
    magma_version: magma-cu116
  - version: 11.7
    magma_version: magma-cu117
pytorch:
  - version: 1.13.0
    conda_channel: pytorch
  - version: 1.12.1
    conda_channel: pytorch-test
