name: linux-test-cpu
on:
  workflow_call:
    secrets:
      HUGGING_FACE_HUB_TOKEN:
        required: false
        description: |
          HF Auth token to avoid rate limits when downloading models or datasets from hub

jobs:
  linux-test-cpu:
    # Don't run on forked repos
    if: github.repository_owner == 'pytorch'
    runs-on: [self-hosted, linux.24xlarge]
    timeout-minutes: 240
    environment: docker-s3-upload
    env:
      CONDA_ENV: "torchbench"
      DOCKER_IMAGE: "ghcr.io/pytorch/torchbench:latest"
      SETUP_SCRIPT: "/workspace/setup_instance.sh"
      TEST_CONFIG: "cpu"
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
    steps:
      - name: "[FB EMPLOYEES] Enable SSH (Click me for login details)"
        uses: pytorch/test-infra/.github/actions/setup-ssh@main
        with:
          github-secret: ${{ secrets.TORCHBENCH_ACCESS_TOKEN }}
      - name: Checkout TorchBench
        uses: actions/checkout@v3
        with:
          path: benchmark
      - name: Pull docker image
        uses: pytorch/test-infra/.github/actions/pull-docker-image@main
        with:
          docker-image: ${{ env.DOCKER_IMAGE }}
      - name: Install and Test TorchBench
        run: |
          container_name=$(docker run \
            -e BASE_CONDA_ENV="${BASE_CONDA_ENV}" \
            -e CONDA_ENV="${CONDA_ENV}" \
            -e SETUP_SCRIPT="${SETUP_SCRIPT}" \
            -e HUGGING_FACE_HUB_TOKEN="${HUGGING_FACE_HUB_TOKEN}" \
            -e TEST_CONFIG="${TEST_CONFIG}" \
            --tty \
            --detach \
            --shm-size=32gb \
            -v "${PWD}/benchmark:/benchmark" \
            -w / \
            "${{ env.DOCKER_IMAGE }}" \
            tail -f /dev/null
          )
          echo "Container name: ${container_name}"
          docker exec -t -w "/" "${container_name}" bash -c "sudo chown -R runner /benchmark; sudo chgrp -R runner /benchmark"
          docker exec -t -w "/benchmark" "${container_name}" bash /benchmark/.ci/torchbench/install.sh
          docker exec -t -w "/benchmark" "${container_name}" bash /benchmark/.ci/torchbench/test.sh
      - name: Teardown Linux
        uses: pytorch/test-infra/.github/actions/teardown-linux@main
        if: always()
