name: linux-test-cpu
on:
  workflow_call:
    secrets:
      HUGGING_FACE_HUB_TOKEN:
        required: false
        description: |
          HF Auth token to avoid rate limits when downloading models or datasets from hub

jobs:
  linux-test-cpu:
    # Don't run on forked repos
    if: github.repository_owner == 'pytorch'
    runs-on: [self-hosted, linux.24xlarge]
    timeout-minutes: 240
    environment: docker-s3-upload
    env:
      BASE_CONDA_ENV: "torchbench"
      CONDA_ENV: "pr-test-cpu"
      DOCKER_IMAGE: "ghcr.io/pytorch/torchbench:latest"
      SETUP_SCRIPT: "/workspace/setup_instance.sh"
      TEST_CONFIG: "cpu"
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
    steps:
      - name: "[FB EMPLOYEES] Enable SSH (Click me for login details)"
        uses: pytorch/test-infra/.github/actions/setup-ssh@main
        with:
          github-secret: ${{ secrets.TORCHBENCH_ACCESS_TOKEN }}
      - name: Checkout TorchBench
        uses: actions/checkout@v3
        with:
          path: benchmark
      - name: Install Conda
        run: |
          cd benchmark
          bash ./.ci/torchbench/install-conda.sh
      - name: Install and Test TorchBench
        run: |
          cd benchmark
          bash .ci/torchbench/install.sh
          bash .ci/torchbench/test.sh
      - name: Teardown Linux
        uses: pytorch/test-infra/.github/actions/teardown-linux@main
        if: always()
