name: linux-test-cuda
on:
  workflow_call:
    secrets:
      HUGGING_FACE_HUB_TOKEN:
        required: false
        description: |
          HF Auth token to avoid rate limits when downloading models or datasets from hub

jobs:
  linux-test-cuda:
    # Don't run on forked repos
    if: github.repository_owner == 'pytorch'
    runs-on: linux.aws.a100
    timeout-minutes: 240
    environment: docker-s3-upload
    env:
      CONDA_ENV: "pr-test-cuda"
      TEST_CONFIG: "cuda"
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
    steps:
      - name: Checkout TorchBench
        uses: actions/checkout@v3
      - name: Install Conda
        run: |
          bash ./.ci/torchbench/install-conda.sh
      - name: Install TorchBench
        run: |
          bash ./.ci/torchbench/install.sh
      - name: Test TorchBench
        run: |
          bash ./.ci/torchbench/test.sh
      - name: Clean up Conda env
        if: always()
        run: |
          . ${HOME}/miniconda3/etc/profile.d/conda.sh
          conda remove -n "${CONDA_ENV}" --all
