name: TorchBench bisection v0.1
on:
  workflow_dispatch:
    inputs:
      issue_name:
        description: "Bisection Issue Name"
        required: true
        default: "example-issue"

jobs:
  bisection:
    if: ${{ github.repository_owner == 'pytorch' }}
    runs-on: [self-hosted, bm-metal]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 0.1
      - name: Bisection
        run: |
          export BISECT_ISSUE=${{ github.event.inputs.issue_name }}
          export WORKDIR=${HOME}/.torchbench/bisection/${BISECT_ISSUE}
          mkdir -p ${WORKDIR}/gh${GITHUB_RUN_ID}
          bash ./.github/scripts/run-bisection.sh
          # Update the result json symbolic link
          if [ -f ${WORKDIR}/output.json ]; then
             rm ${WORKDIR}/output.json
          else
             ln -s ${WORKDIR}/gh${GITHUB_RUN_ID}/output.json ${WORKDIR}/output.json
          fi
