name: TorchBench V3 Dev Infra nightly benchmarking
on:
  workflow_dispatch:
jobs:
  # CUDA 11.6 nightly test
  benchmark-cu116:
    env:
      TORCHBENCH_VER: "v3"
      PYTHON_VER: "3.8"
      CUDA_VER: "11.6"
      MAGMA_VERSION: "magma-cuda116"
      CONDA_ENV_NAME:  "torchbench-v3-devinfra-nightly-ci"
      UB_NAME: "devinfra-nightly"
      CUDA_VERSION: "cu116"
      IS_GHA: 1
      AWS_DEFAULT_REGION: us-east-1
      BUILD_ENVIRONMENT: benchmark-nightly
    runs-on: [ linux.4xlarge.nvidia.gpu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: v2.0
      - name: Create conda env
        run: |
          conda create -y -q --name "${CONDA_ENV_NAME}" python=${{ env.PYTHON_VER }}
      - name: Install PyTorch nightly
        run: |
          . activate "${CONDA_ENV_NAME}"
          # Install dependencies
          pip install requests bs4 argparse gitpython boto3
          # Check if nightly builds are available
          NIGHTLIES=$(python torchbenchmark/util/torch_nightly.py --packages torch)
          # If failed, the script will generate empty result
          if [ -z $NIGHTLIES ]; then
              echo "Torch nightly build failed. Cancel the workflow."
              exit 1
          fi
          # install git-lfs
          conda install -y git-lfs
          # install magma
          conda install -y -c pytorch "${MAGMA_VERSION}"
          # Install PyTorch nightly from pip
          pip install --pre torch torchtext torchvision \
          -f https://download.pytorch.org/whl/nightly/${CUDA_VERSION}/torch_nightly.html
      - name: Install other TorchBench dependencies
        run: |
          . activate "${CONDA_ENV_NAME}"
          python install.py
      - name: Run benchmark
        run: |
          . activate "${CONDA_ENV_NAME}"
          python run_benchmark.py "${UB_NAME}"
      - name: Copy artifact
        run: |
          . activate "${CONDA_ENV_NAME}"
          mkdir -p benchmark-output
          cp -r .userbenchmark/"${UB_NAME}"/* benchmark-output/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Benchmark result
          path: benchmark-output/
