name: TorchBench Model Profiling CI
on:
  pull_request:

env:
  CONDA_ENV: pr-profile

jobs:
  profile-model:
    if: ${{ github.repository_owner == 'pytorch' && contains(github.event.pull_request.body, 'PROFILE_MODEL:') }}
    # List of available instances available in pytorch/.github/scale-config.yml
    runs-on: linux.8xlarge.nvidia.gpu
    # 2 hours
    timeout-minutes: 120
    steps:
      - name: Checkout TorchBench
        uses: actions/checkout@v2
      - name: Create conda environment and install PyTorch nightly
        run: |
          conda create -y -n ${{ env.CONDA_ENV }} python=3.7
          conda activate ${{ env.CONDA_ENV }}
          conda install -y numpy=1.17 requests=2.22 ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six dataclasses tabulate gitpython
          # Install pytorch nightly
          conda install -y -c pytorch-nightly torchtext torchvision cudatoolkit=10.2
          python install.py
