name: TorchBench PR Test for GitHub issue creation
on:
  pull_request:
  workflow_dispatch:

env:
  CONDA_ENV: "torchbench"
  DOCKER_IMAGE: "ghcr.io/pytorch/torchbench:latest"
  SETUP_SCRIPT: "/workspace/setup_instance.sh"
  HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}

jobs:
  pr-test:
    if: ${{ github.repository_owner == 'pytorch' }}
    runs-on: [self-hosted, linux.4xlarge]
    timeout-minutes: 1440 # 24 hours
    environment: docker-s3-upload
    steps:
      - name: Checkout TorchBench
        uses: actions/checkout@v3
        with:
          path: benchmark
      - name: Generate the GH Issue file
        run: |
          echo "Test performance file" > ./benchmark/gh-issue.md
      - name: Create the github issue
        continue-on-error: true
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Test Performance Issue Creation
          token: ${{ secrets.TORCHBENCH_ACCESS_TOKEN }}
          content-filepath: ./benchmark/gh-issue.md
          labels: |
            torchbench-perf-report
      - name: Teardown Linux
        uses: pytorch/test-infra/.github/actions/teardown-linux@main
        if: always()

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
