name: TorchBench PR Test
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  cpu-test:
    uses: ./.github/workflows/_linux-test-cpu.yml
    with:
      timeout-minutes: 240 # 4 hours
  cuda-test:
    uses: ./.github/workflows/_linux-test-cuda.yml
    with:
      timeout-minutes: 240 # 4 hours
