name: Torchao nightly workflow (A100)
on:
  # DEBUG
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '00 18 * * *' # run at 6:00 PM UTC, K8s containers will roll out at 12PM EST

jobs:
  timm:
    if: false
    uses: ./.github/workflows/_linux-benchmark-cuda.yml
    with:
      userbenchmark: torchao
      userbenchmark-run-args: "--ci --dashboard --timm"
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
  torchbench:
    uses: ./.github/workflows/_linux-benchmark-cuda.yml
    with:
      userbenchmark: torchao
      userbenchmark-run-args: "--ci --dashboard --torchbench"
      # TODO (huydhn): Bring back the rest of them
      only: BERT_pytorch
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
  huggingface:
    if: false
    uses: ./.github/workflows/_linux-benchmark-cuda.yml
    with:
      userbenchmark: torchao
      userbenchmark-run-args: "--ci --dashboard --huggingface"
    secrets:
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
